### ISSUE TITLE
conda?

### ISSUE THREAD

**Issue by AntonioBaeza** [fmalmeida/MpGAP#17]
Looks like a great pipeline. Any chance you can have it in conda?

**Comment by mahesh-panchal** [comment]
Or better yet, would you consider adding/merging this to nf-core (https://nf-co.re/)?
All the modules would then support conda, docker, and singularity. 
There's an old workflow that needs some modernization called hybrid-denovo where the assembly/annotation discussions are going on. 
There is going to be an nf-core hackathon in October (https://nf-co.re/events/2021/hackathon-october-2021), where one could get help transforming your modules ready for an nf-core DSL2 workflow. 
It would be really nice to see this integrated into nf-core.

**Comment by fmalmeida** [comment]
Hi @AntonioBaeza  and @mahesh-panchal,

First of all, thanks for your interest in the pipeline.

### about conda

Yes, updating the pipeline to also use conda environments instead of only Docker is definitely in my TODO/whish list.

However, I was not able to fully work on it yet because some of the tools are not yet available in conda. I am not very much of an expert in conda package development. I am still studying on how to help on that and create a bioconda package for the tools that yet don't have it. And I tell you that a help on that would be deeply appreciated.

### about nf-core

About the nf-core consideration, I would gladly merge the pipeline into nf-core. However I have two considerations on it:

1. nf-core says that new pipelines must not overlap of already existent nf-core pipelines. Thus, it may be a problem for bringing the pipeline to nf-core since they already have some of their own.
2. This pipeline "hybrid-denovo" seems to be focused on hybrid assemblies onle, thus I don't know if it'd be of interest for them because MpGAP performs not only hybrid assemblies, but short reads only and long reads only too. Thus, we must properly discuss if it would be a possibility.

I will try to participate on the hackathon that you mentioned to see if the community together can help on solving this problems and work together on the best solution for that: either merging it in nf-core or developing new bioconda packages so that the pipeline can also run with conda-only.

In the mean time, do you know where I could starting discussing it with the nf-core community and developers?

Thanks again for your interests and ideas. Any help is immensely welcomed.

**Comment by mahesh-panchal** [comment]
Re: nf-core

Please join us on slack and discuss this in the #new-pipelines channel (https://nf-co.re/join/slack). 
The primary issues I think are that all tools need to be in bioconda.
Although I mention 'hybrid-denovo', it is an old pipeline and I think one that needs to be replaced. I'm sure the community would benefit a workflow that could support as many types of input as possible, launching, short-read only, long-read only, or hybrid assemblies.

**Comment by fmalmeida** [comment]
I have re-checked the tools in the bioconda channel and it now seems that all the tools are available there. Thus, in the meantime, I will start re-shaping the pipeline so it can either run with Docker and conda as suggested by @AntonioBaeza.

Re: nf-core

Thank you again @mahesh-panchal for the information. I will bring the suggestion and discussion to our group so we can then start discussions with nf-core community.

**Comment by fmalmeida** [comment]
Now that the pipeline has been reconfigured to understand a YAML so it can analyse multiple samples at once. I will start to take a look on the possibility to set the modules to use bioconda channels and bioconda docker images so it has an easy integration for using conda, docker or singularity.

This will be tackled in branch https://github.com/fmalmeida/MpGAP/tree/issue-17-conda

**Comment by fmalmeida** [comment]
Made some tests with a simpler pipeline (https://github.com/fmalmeida/ngs-preprocess) and was able to make it run with docker, conda and singularity.

I will try then to implement this possibility in MpGAP using what I've learnt from the implementation in this other pipeline, focusing on using bioconda packages.

**Comment by fmalmeida** [comment]
Hello guys,

Just to update that I tried to address this issue in PR #25.

This is the first time that I try to implement my pipelines with either conda and singularity at once, moreover, some tools used in it are either only available for linux-64, or its conda packages are neither available nor up-to-date, causing incompatibility with other tools.

Thus, to solve the tools that had this problem, I have made pre-compiled linux-64 binaries of them available inside the main/root pipeline bin directory.

Please, since it is the first time I did it, the `conda profile` must be considered rather experimental and please, do not hesitate if a problem arise.

Read more at: https://github.com/fmalmeida/MpGAP#selecting-between-profiles

😄
