### ISSUE TITLE
100% missing in Busco

### ISSUE THREAD

**Issue by scintilla9** [fmalmeida/MpGAP#54]
Hi Dr Almeida,

I was playing around the pipeline, everything want well, however, I found issue in Busco.
The output summary showed no buscos were found in query genome (100% missing) against bacteria_odb9. I also found some issues in quast github, seems related to LD_LIBRARY_PATH (https://github.com/ablab/quast/issues/88).

I also tried on standalone Busco container (v5.4.7) with bacteria_odb10, and got 100% complete single copy. It confirms that the assembled genome is well.

Could you please kindly check if it could be fixed?

Best,
CW

**Comment by fmalmeida** [comment]
Hi @scintilla9 ,
Thanks for reporting it. I think it might have happened in the last docker image update I made.

I will take a look at this and let you know. Glad tk hear that the assembly is good.

**Comment by fmalmeida** [comment]
Hi @scintilla9 ,
Thank you very much for reporting this error. I have found the problem, and realised that I have done a major mistake a few weeks ago, which I have merged a branch with new features (considered dev) in the `master` branch instead of the `dev` branch.

Luckly, I was able to use the latest tagged version, `v3.1.4` to revert the `master` branch back to its right version and passed on the developmental code to the `dev` branch where it always belonged.

So now, things are supposed to be correct:

* `master` branch and `v3.1.4` working fine
* `dev` branch having the `busco` error which is fine, because I am still working on it and the `docker` image is not final.

Once again, thanks for reporting it.

Can you give a try using one of the following options so I can be sure it is fine and close this ticket?

* `nextflow run fmalmeida/mpgap -r master -latest`
* `nextflow run fmalmeida/mpgap -r v3.1.4 -latest`

**Comment by scintilla9** [comment]
Hi @fmalmeida ,

Sorry for the late reply, I was unavailable for testing the pipeline until yesterday.
The `master` branch /  `v3.1.4` works fine! I got busco result with 95% completeness.  

Thanks for fixing it.

**Comment by fmalmeida** [comment]
Thanks. I will close the ticket.

Also added some merging rules to only allow `PRs` to merge code in `master` to try to avoid this problem in the future.

Thanks for reporting it.
