### ISSUE TITLE
error in running MpGAP with SRR8482585_30X_{1,2}.fastq.gz and SRX5299443_30X.fastq.gz

### ISSUE THREAD

**Issue by CaiBiotech** [fmalmeida/MpGAP#75]
When I tried to test the complete workflow of your code, I found that the case file at https://figshare.com/ndownloader/articles/14036585/versions/4 can pass through the ngs-preprocess pipeline, but when I continue with the MpGAP pipeline, an error occurs. The code I tried is as follows:
nextflow run fmalmeida/mpgap \
  --output mpgap_assmbly \
  --max_cpus 20 \
  --genome_size 6m \
  --input ./mpgap_samplesheet.yml \
  --hybrid-strategy both \
  -profile docker

running log
[.nextflow.log](https://github.com/fmalmeida/MpGAP/files/15190991/default.nextflow.log)

**Comment by fmalmeida** [comment]
Hi @CaiBiotech ,
The error is super odd, specially comming from the dump sofwares, with such message:
```console
Traceback (most recent call last):
    File ".command.sh", line 101, in <module>
      main()
    File ".command.sh", line 69, in main
      raise AssertionError(
  AssertionError: We assume that software versions are the same between all modules. If you see this error-message it means you discovered an edge-case and should open an issue in nf-core/tools.
```

Can you share the contents of the following directory so I can try to find the culprit?
--> `/share/home/dw_user0001/easy_genome/job20240429/work/67/de629a449b02e7d503777c6a1087bb`.

I believe github allows you to share compressed files.

**Comment by fmalmeida** [comment]
That would be very helpful because, when trying to reproduce it, using the test case file you mentioned, which is the same one in the `Quickstart` section of the pipeline's online manual.

When using the commands from there to run it, it finished successfully:
```console
nextflow run fmalmeida/mpgap \
  --output _ASSEMBLY \
  --max_cpus 5 \
  --skip_spades \
  --input "samplesheet.yml" \
  --unicycler_additional_parameters ' --mode conservative ' \
  -profile docker --hybrid_strategy both -r master -latest
```

![image](https://github.com/fmalmeida/MpGAP/assets/7727714/8b726b3e-a8b2-4b59-9690-e1776e94f057)

So, having the directory mentioned would be helpful to try to understand what happened. But, meanwhile, I would suggest you try running again to check if it reproduces.

**Comment by CaiBiotech** [comment]
Updating Nextflow to version 23.10.1 seems to have resolved the issue.  Thank you!

**Comment by fmalmeida** [comment]
Awesome!
I should consider then increasing the “minimum version” required then.
Many thanks for reporting!
